export type AutomationField = {
  name: string;
  label: string;
  type?: "text" | "number" | "date" | "textarea" | "select";
  options?: string[];
  required?: boolean;
  table?: boolean;
};

export type AutomationViewConfig = {
  title: string;
  description: string;
  endpoint: string;
  resource: string;
  module: string;
  statusField?: string;
  searchFields: string[];
  fields: AutomationField[];
  dashboardKeys?: string[];
};

const statuses = ["draft", "active", "inactive", "pending_review", "approved", "rejected", "closed"];
const workflowStates = [
  "Draft",
  "Submitted",
  "Under Review",
  "Approved",
  "Rejected",
  "Executing",
  "Waiting for External Action",
  "Escalated",
  "Completed",
  "Closed",
  "Cancelled",
];
const departments = ["HR", "Finance", "Sales", "Marketing", "Customer Desk", "Technical", "Projects", "Legal", "Operations", "Management"];
const categories = [
  "Enterprise Governance",
  "Data Governance",
  "Information Security",
  "Finance Governance",
  "HR Governance",
  "Procurement Governance",
  "Sales Governance",
  "Legal Governance",
  "Project Governance",
  "Operations Governance",
  "Integration Governance",
  "Risk & Compliance",
];

export const automationViews: Record<string, AutomationViewConfig> = {
  governance: {
    title: "Governance Command Center",
    description: "Enterprise policies, exceptions, acknowledgements, ownership, review cycles, and compliance posture.",
    endpoint: "/api/governance/policies",
    resource: "Policy",
    module: "Governance",
    statusField: "status",
    searchFields: ["policy_name", "policy_code", "category", "owner_role", "compliance_status"],
    dashboardKeys: ["policies", "policy_exceptions", "compliance_controls", "risks"],
    fields: [
      { name: "policy_code", label: "Code", required: true, table: true },
      { name: "policy_name", label: "Policy", required: true, table: true },
      { name: "category", label: "Category", type: "select", options: categories, required: true, table: true },
      { name: "owner_role", label: "Owner Role", table: true },
      { name: "review_cycle_days", label: "Review Days", type: "number", table: true },
      { name: "next_review_date", label: "Next Review", type: "date", table: true },
      { name: "compliance_status", label: "Compliance", type: "select", options: ["compliant", "partial", "non_compliant", "under_review"], table: true },
      { name: "status", label: "Status", type: "select", options: statuses, table: true },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
  sops: {
    title: "SOP Library",
    description: "Departmental and cross-functional operating procedures connected to policies, workflows, evidence, and SLAs.",
    endpoint: "/api/sops",
    resource: "SOP",
    module: "SOP",
    statusField: "status",
    searchFields: ["sop_code", "sop_title", "department", "owner_role"],
    dashboardKeys: ["sops", "policies", "active_workflows"],
    fields: [
      { name: "sop_code", label: "Code", required: true, table: true },
      { name: "sop_title", label: "SOP", required: true, table: true },
      { name: "department", label: "Department", type: "select", options: departments, required: true, table: true },
      { name: "owner_role", label: "Owner Role", table: true },
      { name: "sla_hours", label: "SLA Hours", type: "number", table: true },
      { name: "review_cycle_days", label: "Review Days", type: "number" },
      { name: "next_review_date", label: "Next Review", type: "date", table: true },
      { name: "status", label: "Status", type: "select", options: statuses, table: true },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
  workflows: {
    title: "Workflow Orchestration",
    description: "Executable business process templates and live workflow instances across hire-to-retire, lead-to-cash, procure-to-pay, incidents, contracts, and executive reporting.",
    endpoint: "/api/workflows/instances",
    resource: "Workflow",
    module: "Workflow",
    statusField: "state",
    searchFields: ["instance_name", "workflow_code", "source_module", "owner_role", "state"],
    dashboardKeys: ["active_workflows", "escalated_workflows", "completed_workflows", "workflow_tasks"],
    fields: [
      { name: "workflow_code", label: "Workflow Code", required: true, table: true },
      { name: "instance_name", label: "Instance", required: true, table: true },
      { name: "source_module", label: "Source", type: "select", options: departments, table: true },
      { name: "target_module", label: "Target", type: "select", options: departments, table: true },
      { name: "owner_role", label: "Owner Role", table: true },
      { name: "state", label: "State", type: "select", options: workflowStates, table: true },
      { name: "priority", label: "Priority", type: "select", options: ["low", "medium", "high", "critical"], table: true },
      { name: "due_at", label: "Due", type: "date", table: true },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
  "workflow-templates": {
    title: "Workflow Templates",
    description: "Reusable enterprise process blueprints with stages, automation triggers, escalation logic, and SLA alignment.",
    endpoint: "/api/workflows/templates",
    resource: "Workflow Template",
    module: "Workflow",
    statusField: "status",
    searchFields: ["workflow_code", "workflow_name", "department", "trigger_event"],
    dashboardKeys: ["workflow_templates", "active_workflows", "workflow_tasks"],
    fields: [
      { name: "workflow_code", label: "Code", required: true, table: true },
      { name: "workflow_name", label: "Template", required: true, table: true },
      { name: "department", label: "Department", type: "select", options: departments, table: true },
      { name: "trigger_event", label: "Trigger", table: true },
      { name: "default_sla_hours", label: "SLA Hours", type: "number", table: true },
      { name: "status", label: "Status", type: "select", options: statuses, table: true },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
  approvals: {
    title: "Approval Matrix",
    description: "Amount, risk, department, and role-based authorization rules with separation of duties and delegated approvals.",
    endpoint: "/api/approvals/matrix",
    resource: "Approval Rule",
    module: "Approval",
    statusField: "status",
    searchFields: ["rule_name", "process_name", "department", "approver_role"],
    dashboardKeys: ["pending_approvals", "approval_rules", "overdue_approvals"],
    fields: [
      { name: "rule_name", label: "Rule", required: true, table: true },
      { name: "process_name", label: "Process", required: true, table: true },
      { name: "department", label: "Department", type: "select", options: departments, table: true },
      { name: "approval_level", label: "Level", type: "number", table: true },
      { name: "approver_role", label: "Approver Role", required: true, table: true },
      { name: "amount_threshold", label: "Amount Threshold", type: "number", table: true },
      { name: "risk_threshold", label: "Risk", type: "select", options: ["low", "medium", "high", "critical"], table: true },
      { name: "requires_dual_approval", label: "Dual Approval", type: "select", options: ["true", "false"] },
      { name: "status", label: "Status", type: "select", options: statuses, table: true },
    ],
  },
  events: {
    title: "Enterprise Events",
    description: "Cross-module events that allow HR, CRM, Projects, Finance, IAM, Legal, and Operations to coordinate without direct table mutation.",
    endpoint: "/api/events",
    resource: "Event",
    module: "Events",
    statusField: "status",
    searchFields: ["event_type", "source_module", "target_module", "processed_by", "failure_reason"],
    dashboardKeys: ["events", "failed_events", "active_workflows"],
    fields: [
      { name: "event_type", label: "Event", required: true, table: true },
      { name: "source_module", label: "Source", required: true, table: true },
      { name: "target_module", label: "Target", table: true },
      { name: "status", label: "Status", type: "select", options: ["pending", "processing", "processed", "failed"], table: true },
      { name: "retry_count", label: "Retries", type: "number", table: true },
      { name: "processed_by", label: "Processed By", table: true },
      { name: "failure_reason", label: "Failure Reason", type: "textarea" },
      { name: "payload", label: "Payload JSON", type: "textarea" },
    ],
  },
  audit: {
    title: "Audit & Compliance Log",
    description: "Immutable-style record of sensitive actions, approvals, policy changes, workflow transitions, access changes, and failures.",
    endpoint: "/api/audit/logs",
    resource: "Audit Log",
    module: "Audit",
    statusField: "result",
    searchFields: ["actor", "action", "entity_type", "entity_id", "module", "result"],
    dashboardKeys: ["audit_logs", "compliance_controls", "risks"],
    fields: [
      { name: "actor", label: "Actor", table: true },
      { name: "action", label: "Action", required: true, table: true },
      { name: "entity_type", label: "Entity", required: true, table: true },
      { name: "entity_id", label: "Entity ID", table: true },
      { name: "module", label: "Module", table: true },
      { name: "result", label: "Result", type: "select", options: ["success", "failure", "blocked"], table: true },
      { name: "failure_reason", label: "Failure Reason", type: "textarea" },
    ],
  },
  sla: {
    title: "SLA & Escalation Control",
    description: "SLA policies, timers, breach warnings, escalation paths, and department compliance dashboards.",
    endpoint: "/api/sla/policies",
    resource: "SLA Policy",
    module: "SLA",
    statusField: "status",
    searchFields: ["policy_name", "process_name", "priority", "department"],
    dashboardKeys: ["sla_policies", "sla_breaches", "near_breach_slas", "escalations"],
    fields: [
      { name: "policy_name", label: "Policy", required: true, table: true },
      { name: "process_name", label: "Process", required: true, table: true },
      { name: "department", label: "Department", type: "select", options: departments, table: true },
      { name: "priority", label: "Priority", type: "select", options: ["low", "medium", "high", "critical"], table: true },
      { name: "response_minutes", label: "Response Mins", type: "number", table: true },
      { name: "resolution_minutes", label: "Resolution Mins", type: "number", table: true },
      { name: "warning_minutes_before", label: "Warning Mins", type: "number" },
      { name: "status", label: "Status", type: "select", options: statuses, table: true },
    ],
  },
  iam: {
    title: "IAM Access Control",
    description: "Roles, permissions, access profiles, provisioning status, separation of duties, and quarterly access review evidence.",
    endpoint: "/api/iam/access-profiles",
    resource: "Access Profile",
    module: "IAM",
    statusField: "status",
    searchFields: ["user_name", "department", "role_name", "provisioning_status"],
    dashboardKeys: ["access_profiles", "access_reviews", "pending_approvals"],
    fields: [
      { name: "user_name", label: "User", required: true, table: true },
      { name: "department", label: "Department", type: "select", options: departments, table: true },
      { name: "role_name", label: "Role", required: true, table: true },
      { name: "provisioning_status", label: "Provisioning", type: "select", options: ["requested", "approved", "provisioned", "deactivated", "failed"], table: true },
      { name: "mfa_required", label: "MFA", type: "select", options: ["true", "false"], table: true },
      { name: "privileged", label: "Privileged", type: "select", options: ["true", "false"], table: true },
      { name: "status", label: "Status", type: "select", options: statuses, table: true },
    ],
  },
  compliance: {
    title: "Compliance Controls",
    description: "Control ownership, testing frequency, evidence status, control health, exceptions, and corrective actions.",
    endpoint: "/api/compliance/controls",
    resource: "Control",
    module: "Compliance",
    statusField: "status",
    searchFields: ["control_code", "control_name", "control_area", "owner_role", "effectiveness"],
    dashboardKeys: ["compliance_controls", "risks", "corrective_actions"],
    fields: [
      { name: "control_code", label: "Code", required: true, table: true },
      { name: "control_name", label: "Control", required: true, table: true },
      { name: "control_area", label: "Area", table: true },
      { name: "owner_role", label: "Owner Role", table: true },
      { name: "effectiveness", label: "Effectiveness", type: "select", options: ["effective", "partial", "ineffective", "untested"], table: true },
      { name: "last_tested_date", label: "Last Tested", type: "date", table: true },
      { name: "next_test_date", label: "Next Test", type: "date", table: true },
      { name: "status", label: "Status", type: "select", options: statuses, table: true },
    ],
  },
  risk: {
    title: "Risk Register",
    description: "Enterprise risks with likelihood, impact, scoring, mitigation, residual exposure, owners, and review cadence.",
    endpoint: "/api/risk/register",
    resource: "Risk",
    module: "Risk",
    statusField: "status",
    searchFields: ["risk_code", "risk_title", "department", "owner_role", "risk_status"],
    dashboardKeys: ["risks", "policy_exceptions", "corrective_actions"],
    fields: [
      { name: "risk_code", label: "Code", required: true, table: true },
      { name: "risk_title", label: "Risk", required: true, table: true },
      { name: "department", label: "Department", type: "select", options: departments, table: true },
      { name: "owner_role", label: "Owner Role", table: true },
      { name: "inherent_score", label: "Inherent", type: "number", table: true },
      { name: "residual_score", label: "Residual", type: "number", table: true },
      { name: "risk_status", label: "Risk Status", type: "select", options: ["open", "mitigating", "accepted", "closed"], table: true },
      { name: "status", label: "Status", type: "select", options: statuses, table: true },
    ],
  },
  executive: {
    title: "Executive Automation Cockpit",
    description: "Cross-department performance from governance, workflows, approvals, SLAs, audit, compliance, risk, finance, HR, CRM, projects, and operations.",
    endpoint: "/api/kpis",
    resource: "KPI",
    module: "Executive",
    statusField: "status",
    searchFields: ["kpi_name", "department", "owner_role", "measurement_period"],
    dashboardKeys: ["kpis", "kpi_results", "active_workflows", "sla_breaches", "risks", "pending_approvals"],
    fields: [
      { name: "kpi_name", label: "KPI", required: true, table: true },
      { name: "department", label: "Department", type: "select", options: departments, table: true },
      { name: "owner_role", label: "Owner Role", table: true },
      { name: "target_value", label: "Target", type: "number", table: true },
      { name: "actual_value", label: "Actual", type: "number", table: true },
      { name: "measurement_period", label: "Period", table: true },
      { name: "status", label: "Status", type: "select", options: statuses, table: true },
    ],
  },
};
