import { FieldConfig, ResourceConfig, crmArenas, crmPipelineStages, crmPipelineTypes, crmVerticals, serviceScopes } from "@/lib/resourceConfigs";

const accountSelect: Partial<FieldConfig> = { type: "select", selectEndpoint: "/api/crm/enterprise/accounts", selectLabel: ["company_name"] };
const contactSelect: Partial<FieldConfig> = { type: "select", selectEndpoint: "/api/crm/enterprise/contacts", selectLabel: ["first_name", "last_name"] };
const opportunitySelect: Partial<FieldConfig> = { type: "select", selectEndpoint: "/api/crm/enterprise/opportunities", selectLabel: ["title"] };
const productSelect: Partial<FieldConfig> = { type: "select", selectEndpoint: "/api/crm/enterprise/products", selectLabel: ["product_name"] };
const activeCrmEmployeeSelect: Partial<FieldConfig> = { type: "select", selectEndpoint: "/api/crm/active-employees", selectLabel: ["first_name", "last_name"] };
const activeSalesEmployeeSelect: Partial<FieldConfig> = { type: "select", selectEndpoint: "/api/crm/active-employees?role_group=sales", selectLabel: ["first_name", "last_name"] };
const activeTechnicalEmployeeSelect: Partial<FieldConfig> = { type: "select", selectEndpoint: "/api/crm/active-employees?role_group=technical", selectLabel: ["first_name", "last_name"] };

function cfg(
  key: string,
  title: string,
  description: string,
  resource: string,
  fields: FieldConfig[],
  options: Partial<ResourceConfig> = {}
): ResourceConfig {
  return {
    key,
    title,
    description,
    endpoint: `/api/crm/enterprise/${resource}`,
    analyticsEndpoint: `/api/crm/enterprise/${resource}/__analytics`,
    searchFields: fields.map((field) => field.name),
    statusField: "status",
    workflowActions: [],
    fields,
    ...options,
  };
}

export const crmEnterpriseConfigs: Record<string, ResourceConfig> = {
  "crm.enterprise.accounts": cfg("crm.enterprise.accounts", "Accounts", "Customer accounts, vendors, partners, ownership, industry, country, and status.", "accounts", [
    { name: "business_id", label: "ID", table: true },
    { name: "parent_account_id", label: "Parent Account", ...accountSelect },
    { name: "company_name", label: "Company", required: true, table: true },
    { name: "industry", label: "Industry", table: true },
    { name: "website", label: "Website" },
    { name: "phone", label: "Phone" },
    { name: "email", label: "Email", type: "email", table: true },
    { name: "owner_employee_id", label: "Account Owner", ...activeSalesEmployeeSelect, required: true, table: true },
    { name: "relationship_owner", label: "Owner", table: true },
    { name: "account_manager", label: "AM", table: true },
    { name: "country", label: "Country", table: true },
    { name: "region", label: "Region" },
    { name: "vertical", label: "Vertical", type: "select", options: crmVerticals, table: true },
    { name: "account_type", label: "Type", type: "select", options: ["Customer", "Vendor", "Partner", "Prospect"], table: true },
    { name: "account_status", label: "Status", type: "select", options: ["active", "prospect", "inactive"], table: true, defaultValue: "active" },
    { name: "address", label: "Primary Address", type: "textarea" },
    { name: "billing_address", label: "Billing Address", type: "textarea" },
    { name: "shipping_address", label: "Shipping Address", type: "textarea" },
    { name: "notes", label: "Notes", type: "textarea" },
  ], { statusField: "account_status" }),
  "crm.enterprise.contacts": cfg("crm.enterprise.contacts", "Contacts", "Contact persons, roles, account relationship, phone/email, and communication notes.", "contacts", [
    { name: "account_id", label: "Account", ...accountSelect, table: true },
    { name: "owner_employee_id", label: "Owner", ...activeSalesEmployeeSelect, table: true },
    { name: "first_name", label: "First Name", required: true, table: true },
    { name: "last_name", label: "Last Name", required: true, table: true },
    { name: "job_title", label: "Role", table: true },
    { name: "department", label: "Department", table: true },
    { name: "email", label: "Email", type: "email", table: true },
    { name: "phone", label: "Phone" },
    { name: "contact_role", label: "Contact Role", table: true },
    { name: "is_primary", label: "Primary Contact", type: "checkbox", table: true },
    { name: "unlinked_prospect", label: "Unlinked Prospect", type: "checkbox" },
    { name: "communication_preferences", label: "Communication Preferences JSON", type: "textarea" },
    { name: "tags", label: "Tags / Preferences", table: true },
    { name: "notes", label: "Notes", type: "textarea" },
  ], { statusField: undefined }),
  "crm.enterprise.leads": cfg("crm.enterprise.leads", "Leads", "Lead capture, scoring, source, assignment, qualification, and conversion.", "leads", [
    { name: "business_id", label: "ID", table: true },
    { name: "company_name", label: "Company", table: true },
    { name: "contact_name", label: "Contact", required: true, table: true },
    { name: "email", label: "Email", type: "email", table: true },
    { name: "phone", label: "Phone" },
    { name: "lead_source", label: "Source", required: true, table: true },
    { name: "lead_score", label: "Score", type: "number", table: true, defaultValue: 0 },
    { name: "qualification_status", label: "Qualification", type: "select", options: ["unqualified", "qualified", "disqualified", "converted"], table: true, defaultValue: "unqualified" },
    { name: "owner_employee_id", label: "Owner", ...activeSalesEmployeeSelect, required: true, table: true },
    { name: "assigned_to", label: "Owner", required: true, table: true },
    { name: "duplicate_flag", label: "Duplicate", type: "checkbox", table: true },
    { name: "duplicate_reason", label: "Duplicate Reason" },
    { name: "estimated_value", label: "Value", type: "number", table: true, defaultValue: 0 },
    { name: "expected_close_date", label: "Close Date", type: "date" },
    { name: "pipeline_type", label: "Pipeline Type", type: "select", options: crmPipelineTypes },
    { name: "arena", label: "Arena", type: "select", options: crmArenas },
    { name: "service_scope", label: "Delivery Scope", type: "select", options: serviceScopes },
    { name: "account_country", label: "Country", table: true },
    { name: "account_vertical", label: "Vertical", type: "select", options: crmVerticals },
    { name: "status", label: "Status", type: "select", options: ["New", "Assigned", "Qualified", "Disqualified", "Converted"], required: true, table: true, defaultValue: "New" },
    { name: "notes", label: "Notes", type: "textarea" },
  ], { workflowActions: ["assign", "qualify", "disqualify", "convert"], valueField: "estimated_value" }),
  "crm.enterprise.opportunities": cfg("crm.enterprise.opportunities", "Opportunities", "Pipeline stages, expected value, probability, close date, win/loss, competitors, products, and services.", "opportunities", [
    { name: "business_id", label: "ID", table: true },
    { name: "account_id", label: "Account", ...accountSelect, required: true, table: true },
    { name: "title", label: "Opportunity", required: true, table: true },
    { name: "stage", label: "Stage", type: "select", options: crmPipelineStages, table: true, defaultValue: "Stage 1.a Discovery" },
    { name: "owner_employee_id", label: "Owner", ...activeSalesEmployeeSelect, required: true, table: true },
    { name: "presales_employee_id", label: "Presales", ...activeTechnicalEmployeeSelect, table: true },
    { name: "project_manager_employee_id", label: "Project Manager", ...activeCrmEmployeeSelect },
    { name: "opportunity_value", label: "Value", type: "number", table: true, defaultValue: 0 },
    { name: "probability", label: "Probability %", type: "number", table: true, defaultValue: 0 },
    { name: "expected_close_date", label: "Close Date", type: "date", table: true },
    { name: "actual_close_date", label: "Actual Close", type: "date" },
    { name: "win_loss_reason", label: "Win/Loss Reason", type: "textarea" },
    { name: "competitors", label: "Competitors", type: "textarea" },
    { name: "product_service_ids", label: "Products/Services JSON", type: "textarea" },
    { name: "renewal_date", label: "Renewal", type: "date" },
    { name: "licence_expiry_date", label: "Licence Expiry", type: "date" },
    { name: "owner", label: "Owner", table: true },
    { name: "lpo_document_url", label: "LPO / Contract URL" },
    { name: "handover_status", label: "Handover", table: true },
    { name: "country", label: "Country", table: true },
    { name: "vertical", label: "Vertical", type: "select", options: crmVerticals },
    { name: "pipeline_type", label: "Pipeline Type", type: "select", options: crmPipelineTypes },
    { name: "arena", label: "Arena", type: "select", options: crmArenas },
    { name: "service_scope", label: "Delivery Scope", type: "select", options: serviceScopes },
    { name: "gross_profit", label: "GP", type: "number", table: true, defaultValue: 0 },
    { name: "approval_status", label: "Approval", type: "select", options: ["not_required", "pending", "approved", "rejected"], table: true, defaultValue: "not_required" },
    { name: "status", label: "Status", type: "select", options: ["open", "closed_won", "closed_lost"], table: true, defaultValue: "open" },
    { name: "description", label: "Description / Loss Reason", type: "textarea" },
  ], { workflowActions: ["move-stage", "close-won", "close-lost", "reopen"], valueField: "opportunity_value" }),
  "crm.enterprise.activities": cfg("crm.enterprise.activities", "Activities", "Calls, meetings, emails, follow-ups, reminders, notes, ownership, and completion status.", "activities", [
    { name: "related_type", label: "Related Type", type: "select", options: ["lead", "account", "contact", "opportunity"], required: true, table: true },
    { name: "related_id", label: "Related ID" },
    { name: "activity_type", label: "Type", type: "select", options: ["call", "meeting", "email", "follow-up", "reminder", "note"], required: true, table: true },
    { name: "subject", label: "Subject", required: true, table: true },
    { name: "account_name", label: "Account", table: true },
    { name: "created_by", label: "Owner", table: true },
    { name: "due_date", label: "Due", type: "datetime-local", table: true },
    { name: "status", label: "Status", type: "select", options: ["pending", "scheduled", "completed", "cancelled"], table: true, defaultValue: "pending" },
    { name: "description", label: "Description", type: "textarea" },
  ]),
  "crm.enterprise.tasks": cfg("crm.enterprise.tasks", "Tasks", "CRM task ownership, due dates, priority, and completion.", "tasks", [
    { name: "title", label: "Task", required: true, table: true },
    { name: "related_type", label: "Related Type", type: "select", options: ["lead", "account", "contact", "opportunity", "quote", "contract", "ticket"], table: true },
    { name: "related_id", label: "Related ID" },
    { name: "assigned_employee_id", label: "Assignee", ...activeCrmEmployeeSelect, required: true, table: true },
    { name: "owner_employee_id", label: "Owner", ...activeCrmEmployeeSelect },
    { name: "assigned_to", label: "Owner", table: true },
    { name: "priority", label: "Priority", type: "select", options: ["low", "medium", "high", "critical"], table: true, defaultValue: "medium" },
    { name: "due_date", label: "Due", type: "datetime-local", table: true },
    { name: "status", label: "Status", type: "select", options: ["pending", "in_progress", "completed", "cancelled"], table: true, defaultValue: "pending" },
    { name: "description", label: "Description", type: "textarea" },
  ]),
  "crm.enterprise.products": cfg("crm.enterprise.products", "Products & Services", "Product/service catalog, SKUs, pricing, recurring terms, and licence terms.", "products", [
    { name: "product_code", label: "Code", required: true, table: true },
    { name: "product_name", label: "Product / Service", required: true, table: true },
    { name: "product_type", label: "Type", type: "select", options: ["product", "service", "licence", "subscription", "implementation"], table: true, defaultValue: "service" },
    { name: "sku", label: "SKU", table: true },
    { name: "category", label: "Category", table: true },
    { name: "unit_price", label: "Unit Price", type: "number", table: true, defaultValue: 0 },
    { name: "currency", label: "Currency", defaultValue: "KES" },
    { name: "recurring", label: "Recurring", type: "checkbox", table: true },
    { name: "license_term_months", label: "Licence Term Months", type: "number" },
    { name: "status", label: "Status", type: "select", options: ["active", "inactive", "deleted"], table: true, defaultValue: "active" },
    { name: "notes", label: "Notes", type: "textarea" },
  ], { valueField: "unit_price" }),
  "crm.enterprise.priceBooks": cfg("crm.enterprise.priceBooks", "Price Books", "Regional and effective-date price books.", "price-books", [
    { name: "price_book_name", label: "Price Book", required: true, table: true },
    { name: "currency", label: "Currency", table: true, defaultValue: "KES" },
    { name: "region", label: "Region", table: true },
    { name: "effective_from", label: "Effective From", type: "date" },
    { name: "effective_to", label: "Effective To", type: "date" },
    { name: "status", label: "Status", type: "select", options: ["active", "inactive", "deleted"], table: true, defaultValue: "active" },
    { name: "notes", label: "Notes", type: "textarea" },
  ]),
  "crm.enterprise.quotations": cfg("crm.enterprise.quotations", "Quotations", "Quote approval, versioning, expiry, and calculated totals from line items.", "quotations", [
    { name: "opportunity_id", label: "Opportunity", ...opportunitySelect, table: true },
    { name: "quote_number", label: "Quote No.", required: true, table: true },
    { name: "title", label: "Title", required: true, table: true },
    { name: "owner_employee_id", label: "Prepared By", ...activeSalesEmployeeSelect, required: true, table: true },
    { name: "subtotal", label: "Subtotal", type: "number", table: true, defaultValue: 0 },
    { name: "discount_amount", label: "Discount", type: "number", defaultValue: 0 },
    { name: "tax_amount", label: "Tax", type: "number", defaultValue: 0 },
    { name: "total_amount", label: "Total", type: "number", table: true, defaultValue: 0 },
    { name: "valid_until", label: "Valid Until", type: "date", table: true },
    { name: "version_number", label: "Version", type: "number", table: true, defaultValue: 1 },
    { name: "approval_required", label: "Approval Required", type: "checkbox", table: true },
    { name: "approval_status", label: "Approval", type: "select", options: ["draft", "pending", "approved", "rejected", "not_required"], table: true, defaultValue: "draft" },
    { name: "created_by", label: "Prepared By", table: true },
    { name: "approved_by_employee_id", label: "Approver", ...activeCrmEmployeeSelect },
    { name: "approved_by", label: "Approved By" },
    { name: "status", label: "Status", type: "select", options: ["draft", "submitted", "approved", "rejected", "expired", "accepted"], table: true, defaultValue: "draft" },
  ], { workflowActions: ["submit", "approve", "reject", "revise", "expire", "accept"], valueField: "total_amount" }),
  "crm.enterprise.quoteLines": cfg("crm.enterprise.quoteLines", "Quote Line Items", "Products/services, quantities, discounts, taxes, and calculated line totals.", "quote-line-items", [
    { name: "quotation_id", label: "Quote", type: "select", selectEndpoint: "/api/crm/enterprise/quotations", selectLabel: ["quote_number"], required: true, table: true },
    { name: "product_service_id", label: "Product / Service", ...productSelect, required: true, table: true },
    { name: "quantity", label: "Qty", type: "number", table: true, defaultValue: 1 },
    { name: "unit_price", label: "Unit Price", type: "number", table: true, defaultValue: 0 },
    { name: "discount_percent", label: "Discount %", type: "number", defaultValue: 0 },
    { name: "tax_percent", label: "Tax %", type: "number", defaultValue: 0 },
    { name: "line_total", label: "Line Total", type: "number", table: true, defaultValue: 0 },
    { name: "status", label: "Status", type: "select", options: ["active", "inactive"], table: true, defaultValue: "active" },
    { name: "line_description", label: "Description", type: "textarea" },
  ], { valueField: "line_total" }),
  "crm.enterprise.contracts": cfg("crm.enterprise.contracts", "Contracts", "Customer contracts, SLA linkage, renewal dates, reminders, and documents.", "contracts", [
    { name: "contract_number", label: "Contract No.", required: true, table: true },
    { name: "account_id", label: "Account", ...accountSelect, required: true, table: true },
    { name: "opportunity_id", label: "Opportunity", ...opportunitySelect },
    { name: "contract_title", label: "Contract", required: true, table: true },
    { name: "contract_type", label: "Type", table: true },
    { name: "start_date", label: "Start", type: "date", required: true, table: true },
    { name: "end_date", label: "End", type: "date" },
    { name: "renewal_date", label: "Renewal", type: "date", table: true },
    { name: "contract_value", label: "Value", type: "number", table: true, defaultValue: 0 },
    { name: "document_url", label: "Document URL" },
    { name: "renewal_reminder_days", label: "Reminder Days", type: "number", defaultValue: 30 },
    { name: "status", label: "Status", type: "select", options: ["draft", "active", "renewed", "terminated", "expired"], table: true, defaultValue: "draft" },
    { name: "notes", label: "Notes", type: "textarea" },
  ], { workflowActions: ["activate", "renew", "terminate", "expire"], valueField: "contract_value" }),
  "crm.enterprise.tickets": cfg("crm.enterprise.tickets", "Tickets", "Customer support tickets, priorities, SLA status, escalation, and resolution.", "tickets", [
    { name: "account_id", label: "Account", ...accountSelect, table: true },
    { name: "contact_id", label: "Contact", ...contactSelect },
    { name: "ticket_number", label: "Ticket No.", table: true },
    { name: "issue_title", label: "Issue", required: true, table: true },
    { name: "category", label: "Category", type: "select", options: ["Incident", "Request", "Problem", "Change", "Question", "Escalation"], table: true },
    { name: "solution", label: "Solution", table: true },
    { name: "severity", label: "Priority", type: "select", options: ["low", "medium", "high", "critical"], table: true, defaultValue: "medium" },
    { name: "assigned_engineer", label: "Owner", table: true },
    { name: "technical_lead", label: "Lead" },
    { name: "sla_status", label: "SLA", type: "select", options: ["on_track", "breached"], table: true, defaultValue: "on_track" },
    { name: "response_due_at", label: "Response Due", type: "datetime-local" },
    { name: "resolution_due_at", label: "Resolution Due", type: "datetime-local" },
    { name: "escalated_at", label: "Escalated At", type: "datetime-local" },
    { name: "resolved_at", label: "Resolved At", type: "datetime-local" },
    { name: "resolution", label: "Resolution", type: "textarea" },
    { name: "status", label: "Status", type: "select", options: ["open", "assigned", "escalated", "resolved", "closed"], table: true, defaultValue: "open" },
    { name: "notes", label: "Notes", type: "textarea" },
  ], { workflowActions: ["assign", "escalate", "resolve", "close", "reopen"] }),
  "crm.enterprise.campaigns": cfg("crm.enterprise.campaigns", "Campaigns", "Marketing campaigns, targets, lead generation, ROI, and responses.", "campaigns", [
    { name: "campaign_name", label: "Campaign", required: true, table: true },
    { name: "campaign_type", label: "Type", table: true },
    { name: "owner", label: "Owner", table: true },
    { name: "start_date", label: "Start", type: "date" },
    { name: "end_date", label: "End", type: "date" },
    { name: "budget_amount", label: "Budget", type: "number", table: true, defaultValue: 0 },
    { name: "actual_cost", label: "Actual Cost", type: "number", defaultValue: 0 },
    { name: "expected_revenue", label: "Expected Revenue", type: "number", table: true, defaultValue: 0 },
    { name: "generated_leads", label: "Leads", type: "number", table: true, defaultValue: 0 },
    { name: "campaign_roi", label: "ROI", type: "number", table: true, defaultValue: 0 },
    { name: "status", label: "Status", type: "select", options: ["draft", "launched", "paused", "completed", "deleted"], table: true, defaultValue: "draft" },
    { name: "notes", label: "Notes", type: "textarea" },
  ], { workflowActions: ["launch", "pause", "complete"], valueField: "expected_revenue" }),
  "crm.enterprise.campaignResponses": cfg("crm.enterprise.campaignResponses", "Campaign Responses", "Target account/contact responses and lead generation.", "campaign-responses", [
    { name: "campaign_id", label: "Campaign", type: "select", selectEndpoint: "/api/crm/enterprise/campaigns", selectLabel: ["campaign_name"], required: true, table: true },
    { name: "account_id", label: "Account", ...accountSelect },
    { name: "contact_id", label: "Contact", ...contactSelect },
    { name: "response_type", label: "Response", required: true, table: true },
    { name: "lead_created", label: "Lead Created", type: "checkbox", table: true },
    { name: "status", label: "Status", type: "select", options: ["logged", "converted", "ignored"], table: true, defaultValue: "logged" },
    { name: "notes", label: "Notes", type: "textarea" },
  ]),
  "crm.enterprise.approvalRules": cfg("crm.enterprise.approvalRules", "Approval Rules", "Quote, discount, deal, contract, and custom approval thresholds.", "approval-rules", [
    { name: "rule_name", label: "Rule", required: true, table: true },
    { name: "module", label: "Module", type: "select", options: ["quote", "discount", "deal", "contract", "custom"], required: true, table: true },
    { name: "threshold_amount", label: "Amount Threshold", type: "number", table: true, defaultValue: 0 },
    { name: "discount_threshold_percent", label: "Discount %", type: "number", table: true, defaultValue: 0 },
    { name: "approver_role", label: "Approver Role", table: true },
    { name: "status", label: "Status", type: "select", options: ["active", "inactive"], table: true, defaultValue: "active" },
    { name: "notes", label: "Notes", type: "textarea" },
  ]),
  "crm.enterprise.pipelineRules": cfg("crm.enterprise.pipelineRules", "Pipeline Rules", "Configurable pipeline stages, order, probabilities, and closed stage flags.", "pipeline-stage-rules", [
    { name: "pipeline_name", label: "Pipeline", table: true, defaultValue: "default" },
    { name: "stage_name", label: "Stage", required: true, table: true },
    { name: "stage_order", label: "Order", type: "number", required: true, table: true },
    { name: "probability", label: "Probability", type: "number", table: true, defaultValue: 0 },
    { name: "is_closed_stage", label: "Closed Stage", type: "checkbox", table: true },
    { name: "status", label: "Status", type: "select", options: ["active", "inactive"], table: true, defaultValue: "active" },
  ]),
  "crm.enterprise.auditLogs": cfg("crm.enterprise.auditLogs", "Audit Logs", "Sensitive CRM action history.", "audit-logs", [
    { name: "actor_email", label: "Actor", table: true },
    { name: "action", label: "Action", table: true },
    { name: "entity_type", label: "Entity", table: true },
    { name: "entity_id", label: "Record ID" },
    { name: "summary", label: "Summary", type: "textarea", table: true },
  ], { workflowActions: [] }),
};

export const crmModuleGroups = {
  accounts: ["crm.enterprise.accounts", "crm.enterprise.contacts"],
  leads: ["crm.enterprise.leads"],
  pipeline: ["crm.enterprise.opportunities"],
  activities: ["crm.enterprise.activities", "crm.enterprise.tasks"],
  commercial: ["crm.enterprise.products", "crm.enterprise.priceBooks", "crm.enterprise.quotations", "crm.enterprise.quoteLines"],
  contracts: ["crm.enterprise.contracts"],
  support: ["crm.enterprise.tickets"],
  campaigns: ["crm.enterprise.campaigns", "crm.enterprise.campaignResponses"],
  approvals: ["crm.enterprise.approvalRules", "crm.enterprise.pipelineRules", "crm.enterprise.auditLogs"],
};
