import { FieldConfig, ResourceConfig, crmDepartments, roleCategories } from "@/lib/resourceConfigs";

const employeeSelect: Partial<FieldConfig> = {
  type: "select",
  selectEndpoint: "/api/hrm/enterprise/employees",
  selectLabel: ["first_name", "last_name"],
};

const departmentOptions = crmDepartments;
const commonStatuses = ["draft", "pending", "approved", "rejected", "cancelled", "locked", "open", "active", "inactive"];

function cfg(
  key: string,
  title: string,
  description: string,
  resource: string,
  fields: FieldConfig[],
  options: Partial<ResourceConfig> = {}
): ResourceConfig {
  return {
    key,
    title,
    description,
    endpoint: `/api/hrm/enterprise/${resource}`,
    analyticsEndpoint: `/api/hrm/enterprise/${resource}/__analytics`,
    searchFields: fields.map((field) => field.name),
    statusField: "status",
    workflowActions: ["submit", "approve", "reject", "cancel", "lock", "unlock"],
    fields,
    ...options,
  };
}

export const hrmEnterpriseConfigs: Record<string, ResourceConfig> = {
  "hrm.enterprise.companies": cfg("hrm.enterprise.companies", "Companies", "Legal company profiles and operating entities.", "companies", [
    { name: "company_code", label: "Code", required: true, table: true },
    { name: "company_name", label: "Company", required: true, table: true },
    { name: "legal_name", label: "Legal Name", table: true },
    { name: "tax_id", label: "Tax ID" },
    { name: "country", label: "Country", table: true },
    { name: "currency", label: "Currency", table: true, defaultValue: "KES" },
    { name: "status", label: "Status", type: "select", options: ["active", "inactive", "deleted"], table: true, defaultValue: "active" },
  ]),
  "hrm.enterprise.branches": cfg("hrm.enterprise.branches", "Branches", "Branch and office locations linked to company structure.", "branches", [
    { name: "company_id", label: "Company", type: "select", selectEndpoint: "/api/hrm/enterprise/companies", selectLabel: ["company_name"] },
    { name: "branch_code", label: "Code", required: true, table: true },
    { name: "branch_name", label: "Branch", required: true, table: true },
    { name: "country", label: "Country", table: true },
    { name: "city", label: "City", table: true },
    { name: "address", label: "Address", type: "textarea" },
    { name: "status", label: "Status", type: "select", options: ["active", "inactive", "deleted"], table: true, defaultValue: "active" },
  ]),
  "hrm.enterprise.costCenters": cfg("hrm.enterprise.costCenters", "Cost Centers", "Cost ownership for departments, payroll, budgets, and projects.", "cost-centers", [
    { name: "cost_center_code", label: "Code", required: true, table: true },
    { name: "cost_center_name", label: "Cost Center", required: true, table: true },
    { name: "department", label: "Department", type: "select", options: departmentOptions, table: true },
    { name: "owner_employee_id", label: "Owner", ...employeeSelect, table: true },
    { name: "budget_owner", label: "Budget Owner" },
    { name: "status", label: "Status", type: "select", options: ["active", "inactive", "deleted"], table: true, defaultValue: "active" },
  ]),
  "hrm.enterprise.jobGrades": cfg("hrm.enterprise.jobGrades", "Job Grades", "Salary bands, grade levels, and job group controls.", "job-grades", [
    { name: "grade_code", label: "Code", required: true, table: true },
    { name: "grade_name", label: "Grade", required: true, table: true },
    { name: "level", label: "Level", type: "number", table: true },
    { name: "min_salary", label: "Min Salary", type: "number" },
    { name: "max_salary", label: "Max Salary", type: "number", table: true },
    { name: "currency", label: "Currency", defaultValue: "KES" },
    { name: "status", label: "Status", type: "select", options: ["active", "inactive", "deleted"], table: true, defaultValue: "active" },
  ]),
  "hrm.enterprise.contracts": cfg("hrm.enterprise.contracts", "Employment Contracts", "Employment agreements, terms, renewal dates, and signing status.", "contracts", [
    { name: "employee_id", label: "Employee", ...employeeSelect, required: true, table: true },
    { name: "contract_number", label: "Contract No.", required: true, table: true },
    { name: "contract_type", label: "Type", type: "select", options: ["permanent", "fixed_term", "contractor", "internship", "consultant"], required: true, table: true },
    { name: "start_date", label: "Start", type: "date", required: true, table: true },
    { name: "end_date", label: "End", type: "date", table: true },
    { name: "signed_document_url", label: "Document URL" },
    { name: "status", label: "Status", type: "select", options: commonStatuses, table: true, defaultValue: "draft" },
    { name: "notes", label: "Notes", type: "textarea" },
  ]),
  "hrm.enterprise.emergencyContacts": cfg("hrm.enterprise.emergencyContacts", "Emergency Contacts", "Next-of-kin and emergency contact register.", "emergency-contacts", [
    { name: "employee_id", label: "Employee", ...employeeSelect, required: true, table: true },
    { name: "contact_name", label: "Contact", required: true, table: true },
    { name: "relationship", label: "Relationship", required: true, table: true },
    { name: "phone", label: "Phone", required: true, table: true },
    { name: "email", label: "Email", type: "email" },
    { name: "address", label: "Address", type: "textarea" },
    { name: "is_primary", label: "Primary", type: "checkbox", table: true },
    { name: "status", label: "Status", type: "select", options: ["active", "inactive", "deleted"], table: true, defaultValue: "active" },
  ]),
  "hrm.enterprise.roles": cfg("hrm.enterprise.roles", "HR Roles", "HRM role definitions used by policy and access control.", "roles", [
    { name: "role_code", label: "Code", required: true, table: true },
    { name: "role_name", label: "Role", required: true, table: true },
    { name: "role_scope", label: "Scope", table: true, defaultValue: "hrm" },
    { name: "description", label: "Description", type: "textarea" },
    { name: "status", label: "Status", type: "select", options: ["active", "inactive"], table: true, defaultValue: "active" },
  ]),
  "hrm.enterprise.permissions": cfg("hrm.enterprise.permissions", "Permissions", "Fine-grained HRM permissions by module and action.", "permissions", [
    { name: "permission_code", label: "Code", required: true, table: true },
    { name: "module", label: "Module", required: true, table: true },
    { name: "action", label: "Action", type: "select", options: ["read", "create", "update", "delete", "approve", "reject", "lock", "unlock", "export"], required: true, table: true },
    { name: "description", label: "Description", type: "textarea" },
    { name: "status", label: "Status", type: "select", options: ["active", "inactive"], table: true, defaultValue: "active" },
  ]),
  "hrm.enterprise.userLinks": cfg("hrm.enterprise.userLinks", "User-Employee Links", "Connect login accounts to one active internal employee record.", "user-employee-links", [
    { name: "user_id", label: "User ID", required: true, table: true },
    { name: "employee_id", label: "Employee", ...employeeSelect, required: true, table: true },
    { name: "status", label: "Status", type: "select", options: ["active", "inactive"], table: true, defaultValue: "active" },
    { name: "notes", label: "Notes", type: "textarea" },
  ]),
  "hrm.enterprise.auditLogs": cfg("hrm.enterprise.auditLogs", "Audit Logs", "Sensitive HR and payroll action history.", "audit-logs", [
    { name: "actor_email", label: "Actor", table: true },
    { name: "action", label: "Action", table: true },
    { name: "entity_type", label: "Entity", table: true },
    { name: "entity_id", label: "Record ID" },
    { name: "sensitivity", label: "Sensitivity", table: true },
    { name: "summary", label: "Summary", type: "textarea", table: true },
  ], { workflowActions: [] }),
  "hrm.enterprise.leaveTypes": cfg("hrm.enterprise.leaveTypes", "Leave Types", "Leave categories such as annual, sick, compassionate, maternity, and unpaid leave.", "leave-types", [
    { name: "leave_code", label: "Code", required: true, table: true },
    { name: "leave_name", label: "Leave Type", required: true, table: true },
    { name: "paid", label: "Paid", type: "checkbox", table: true, defaultValue: true },
    { name: "status", label: "Status", type: "select", options: ["active", "inactive"], table: true, defaultValue: "active" },
  ]),
  "hrm.enterprise.leavePolicies": cfg("hrm.enterprise.leavePolicies", "Leave Policies", "Entitlements, accruals, carry-forward, and negative balance controls.", "leave-policies", [
    { name: "policy_name", label: "Policy", required: true, table: true },
    { name: "leave_type_id", label: "Leave Type", type: "select", selectEndpoint: "/api/hrm/enterprise/leave-types", selectLabel: ["leave_name"] },
    { name: "annual_entitlement", label: "Annual Days", type: "number", table: true },
    { name: "accrual_frequency", label: "Accrual", type: "select", options: ["monthly", "quarterly", "annual"], table: true, defaultValue: "monthly" },
    { name: "allow_negative_balance", label: "Allow Negative", type: "checkbox" },
    { name: "max_negative_days", label: "Max Negative Days", type: "number" },
    { name: "carry_forward_allowed", label: "Carry Forward", type: "checkbox" },
    { name: "carry_forward_limit", label: "Carry Limit", type: "number" },
    { name: "applies_to_department", label: "Department", type: "select", options: departmentOptions },
    { name: "status", label: "Status", type: "select", options: ["active", "inactive"], table: true, defaultValue: "active" },
  ]),
  "hrm.enterprise.leaveBlackouts": cfg("hrm.enterprise.leaveBlackouts", "Leave Blackout Dates", "Periods where leave is restricted for business reasons.", "leave-blackout-dates", [
    { name: "blackout_name", label: "Blackout", required: true, table: true },
    { name: "start_date", label: "Start", type: "date", required: true, table: true },
    { name: "end_date", label: "End", type: "date", required: true, table: true },
    { name: "applies_to_department", label: "Department", type: "select", options: departmentOptions, table: true },
    { name: "reason", label: "Reason", type: "textarea" },
    { name: "status", label: "Status", type: "select", options: ["active", "inactive"], table: true, defaultValue: "active" },
  ]),
  "hrm.enterprise.shifts": cfg("hrm.enterprise.shifts", "Shifts", "Shift definitions, start/end times, and grace minutes.", "shifts", [
    { name: "shift_code", label: "Code", required: true, table: true },
    { name: "shift_name", label: "Shift", required: true, table: true },
    { name: "start_time", label: "Start", type: "time", required: true, table: true },
    { name: "end_time", label: "End", type: "time", required: true, table: true },
    { name: "grace_minutes", label: "Grace Minutes", type: "number", table: true, defaultValue: 0 },
    { name: "status", label: "Status", type: "select", options: ["active", "inactive"], table: true, defaultValue: "active" },
  ]),
  "hrm.enterprise.timesheets": cfg("hrm.enterprise.timesheets", "Timesheets", "Period timesheets, regular hours, overtime, approval, and locking.", "timesheets", [
    { name: "employee_id", label: "Employee", ...employeeSelect, required: true, table: true },
    { name: "period_start", label: "Period Start", type: "date", required: true, table: true },
    { name: "period_end", label: "Period End", type: "date", required: true, table: true },
    { name: "regular_hours", label: "Regular Hours", type: "number", table: true, defaultValue: 0 },
    { name: "overtime_hours", label: "Overtime", type: "number", table: true, defaultValue: 0 },
    { name: "approved_by", label: "Approved By", ...employeeSelect },
    { name: "status", label: "Status", type: "select", options: commonStatuses, table: true, defaultValue: "draft" },
    { name: "notes", label: "Notes", type: "textarea" },
  ], { valueField: "regular_hours" }),
  "hrm.enterprise.overtime": cfg("hrm.enterprise.overtime", "Overtime Requests", "Overtime submission, approval, and manager controls.", "overtime-requests", [
    { name: "employee_id", label: "Employee", ...employeeSelect, required: true, table: true },
    { name: "overtime_date", label: "Date", type: "date", required: true, table: true },
    { name: "hours", label: "Hours", type: "number", required: true, table: true },
    { name: "reason", label: "Reason", type: "textarea" },
    { name: "approved_by", label: "Approved By", ...employeeSelect },
    { name: "status", label: "Status", type: "select", options: commonStatuses, table: true, defaultValue: "draft" },
    { name: "approval_comments", label: "Comments", type: "textarea" },
  ], { valueField: "hours" }),
  "hrm.enterprise.holidays": cfg("hrm.enterprise.holidays", "Holiday Calendar", "Country and branch holidays used by leave and attendance.", "holidays", [
    { name: "holiday_name", label: "Holiday", required: true, table: true },
    { name: "holiday_date", label: "Date", type: "date", required: true, table: true },
    { name: "country", label: "Country", table: true },
    { name: "branch", label: "Branch", table: true },
    { name: "status", label: "Status", type: "select", options: ["active", "inactive"], table: true, defaultValue: "active" },
  ]),
  "hrm.enterprise.attendancePeriods": cfg("hrm.enterprise.attendancePeriods", "Attendance Periods", "Attendance period approval and locking.", "attendance-periods", [
    { name: "period_name", label: "Period", required: true, table: true },
    { name: "start_date", label: "Start", type: "date", required: true, table: true },
    { name: "end_date", label: "End", type: "date", required: true, table: true },
    { name: "locked_by", label: "Locked By", ...employeeSelect },
    { name: "status", label: "Status", type: "select", options: ["open", "pending", "approved", "locked"], table: true, defaultValue: "open" },
  ]),
  "hrm.enterprise.salaryStructures": cfg("hrm.enterprise.salaryStructures", "Salary Structures", "Configurable salary structures separate from payroll processing.", "salary-structures", [
    { name: "employee_id", label: "Employee", ...employeeSelect, required: true, table: true },
    { name: "structure_name", label: "Structure", required: true, table: true },
    { name: "base_salary", label: "Base Salary", type: "number", required: true, table: true },
    { name: "currency", label: "Currency", defaultValue: "KES" },
    { name: "pay_frequency", label: "Frequency", type: "select", options: ["monthly", "weekly", "daily", "annual"], table: true, defaultValue: "monthly" },
    { name: "effective_from", label: "Effective From", type: "date", required: true },
    { name: "effective_to", label: "Effective To", type: "date" },
    { name: "status", label: "Status", type: "select", options: commonStatuses, table: true, defaultValue: "draft" },
  ], { valueField: "base_salary" }),
  "hrm.enterprise.payrollPeriods": cfg("hrm.enterprise.payrollPeriods", "Payroll Periods", "Payroll month/period control with approval and lock states.", "payroll-periods", [
    { name: "period_code", label: "Period", required: true, table: true },
    { name: "start_date", label: "Start", type: "date", required: true, table: true },
    { name: "end_date", label: "End", type: "date", required: true, table: true },
    { name: "approved_by", label: "Approved By", ...employeeSelect },
    { name: "status", label: "Status", type: "select", options: ["open", "pending", "approved", "locked"], table: true, defaultValue: "open" },
  ]),
  "hrm.enterprise.payrollRuns": cfg("hrm.enterprise.payrollRuns", "Payroll Runs", "Payroll batches, totals, approvals, and final locking.", "payroll-runs", [
    { name: "payroll_period_id", label: "Payroll Period", type: "select", selectEndpoint: "/api/hrm/enterprise/payroll-periods", selectLabel: ["period_code"], required: true, table: true },
    { name: "run_number", label: "Run No.", required: true, table: true },
    { name: "total_gross", label: "Gross", type: "number", table: true, defaultValue: 0 },
    { name: "total_net", label: "Net", type: "number", table: true, defaultValue: 0 },
    { name: "approved_by", label: "Approved By", ...employeeSelect },
    { name: "status", label: "Status", type: "select", options: commonStatuses, table: true, defaultValue: "draft" },
  ], { valueField: "total_net" }),
  "hrm.enterprise.payslips": cfg("hrm.enterprise.payslips", "Payslips", "Employee payslips generated from approved payroll runs.", "payslips", [
    { name: "payroll_run_id", label: "Payroll Run", type: "select", selectEndpoint: "/api/hrm/enterprise/payroll-runs", selectLabel: ["run_number"], required: true, table: true },
    { name: "employee_id", label: "Employee", ...employeeSelect, required: true, table: true },
    { name: "gross_pay", label: "Gross", type: "number", table: true, defaultValue: 0 },
    { name: "net_pay", label: "Net", type: "number", table: true, defaultValue: 0 },
    { name: "payslip_url", label: "Payslip URL" },
    { name: "status", label: "Status", type: "select", options: commonStatuses, table: true, defaultValue: "draft" },
  ], { valueField: "net_pay" }),
  "hrm.enterprise.payrollComponents": cfg("hrm.enterprise.payrollComponents", "Payroll Components", "Configurable allowances, deductions, benefits, and statutory components.", "payroll-components", [
    { name: "component_code", label: "Code", required: true, table: true },
    { name: "component_name", label: "Component", required: true, table: true },
    { name: "component_type", label: "Type", type: "select", options: ["allowance", "deduction", "benefit", "statutory"], required: true, table: true },
    { name: "taxable", label: "Taxable", type: "checkbox", table: true },
    { name: "status", label: "Status", type: "select", options: ["active", "inactive"], table: true, defaultValue: "active" },
  ]),
  "hrm.enterprise.payrollAdjustments": cfg("hrm.enterprise.payrollAdjustments", "Payroll Adjustments", "Formal retroactive corrections for locked payroll records.", "payroll-adjustments", [
    { name: "employee_id", label: "Employee", ...employeeSelect, required: true, table: true },
    { name: "payroll_period_id", label: "Payroll Period", type: "select", selectEndpoint: "/api/hrm/enterprise/payroll-periods", selectLabel: ["period_code"] },
    { name: "adjustment_type", label: "Type", type: "select", options: ["earning", "deduction", "correction", "reversal"], required: true, table: true },
    { name: "amount", label: "Amount", type: "number", required: true, table: true },
    { name: "reason", label: "Reason", type: "textarea", required: true },
    { name: "approved_by", label: "Approved By", ...employeeSelect },
    { name: "status", label: "Status", type: "select", options: commonStatuses, table: true, defaultValue: "draft" },
  ], { valueField: "amount" }),
  "hrm.enterprise.jobRequisitions": cfg("hrm.enterprise.jobRequisitions", "Job Requisitions", "Hiring requests and approval workflow.", "job-requisitions", [
    { name: "job_title", label: "Job Title", required: true, table: true },
    { name: "department", label: "Department", type: "select", options: departmentOptions, required: true, table: true },
    { name: "branch", label: "Branch", table: true },
    { name: "business_unit", label: "Business Unit", table: true },
    { name: "reporting_manager_id", label: "Reporting Manager", ...employeeSelect },
    { name: "hiring_manager_id", label: "Hiring Manager", ...employeeSelect },
    { name: "vacancies", label: "Vacancies", type: "number", table: true, defaultValue: 1 },
    { name: "employment_type", label: "Employment Type", table: true, defaultValue: "Permanent" },
    { name: "salary_band", label: "Salary Band", table: true },
    { name: "budget_code", label: "Budget Code" },
    { name: "reason_for_hire", label: "Reason", type: "textarea", required: true },
    { name: "required_start_date", label: "Required Start", type: "date", table: true },
    { name: "job_description", label: "Job Description", type: "textarea" },
    { name: "approval_status", label: "Approval", table: true, defaultValue: "pending" },
    { name: "status", label: "Status", table: true, defaultValue: "draft" },
  ], {
    endpoint: "/api/hrm/recruitment/requisitions",
    analyticsEndpoint: "/api/hrm/recruitment/requisitions/__analytics",
    statusField: "approval_status",
    workflowActions: ["approve", "reject"],
  }),
  "hrm.enterprise.jobOpenings": cfg("hrm.enterprise.jobOpenings", "Job Openings", "Published openings linked to requisitions.", "job-openings", [
    { name: "requisition_id", label: "Requisition", type: "select", selectEndpoint: "/api/hrm/recruitment/requisitions", selectLabel: ["job_title"], required: true, table: true },
    { name: "job_title", label: "Job Title", required: true, table: true },
    { name: "department", label: "Department", type: "select", options: departmentOptions, table: true },
    { name: "employment_type", label: "Employment Type", table: true },
    { name: "salary_band", label: "Salary Band", table: true },
    { name: "description", label: "Description", type: "textarea" },
    { name: "closing_date", label: "Closing", type: "date", table: true },
    { name: "status", label: "Status", table: true, defaultValue: "draft" },
  ], {
    endpoint: "/api/hrm/recruitment/openings",
    analyticsEndpoint: "/api/hrm/recruitment/openings/__analytics",
    workflowActions: ["publish", "close"],
  }),
  "hrm.enterprise.candidates": cfg("hrm.enterprise.candidates", "Candidates", "Candidate profiles for ATS and recruitment pipelines.", "candidates", [
    { name: "candidate_name", label: "Candidate", required: true, table: true },
    { name: "candidate_email", label: "Email", type: "email", table: true },
    { name: "candidate_phone", label: "Phone" },
    { name: "source_channel", label: "Source", type: "select", options: ["Referral", "LinkedIn", "Website", "Agency", "Job Board", "Direct"], table: true },
    { name: "recruitment_stage", label: "Stage", table: true, defaultValue: "candidate_profile" },
    { name: "application_status", label: "Status", table: true, defaultValue: "active" },
    { name: "notes", label: "Notes", type: "textarea" },
  ], {
    endpoint: "/api/hrm/recruitment/candidates",
    analyticsEndpoint: "/api/hrm/recruitment/candidates/__analytics",
    statusField: "application_status",
    workflowActions: [],
  }),
  "hrm.enterprise.applications": cfg("hrm.enterprise.applications", "Applications", "Candidate applications and recruitment stage tracking.", "applications", [
    { name: "opening_id", label: "Opening", type: "select", selectEndpoint: "/api/hrm/recruitment/openings", selectLabel: ["job_title"], required: true, table: true },
    { name: "candidate_name", label: "Candidate", required: true, table: true },
    { name: "candidate_email", label: "Email", type: "email", required: true, table: true },
    { name: "candidate_phone", label: "Phone" },
    { name: "expected_salary", label: "Expected Salary", type: "number" },
    { name: "availability_date", label: "Availability", type: "date" },
    { name: "application_date", label: "Applied", type: "date", table: true },
    { name: "recruitment_stage", label: "Stage", table: true, defaultValue: "application_received" },
    { name: "application_status", label: "Status", table: true, defaultValue: "applied" },
    { name: "total_score", label: "Score", type: "number", table: true },
  ], {
    endpoint: "/api/hrm/recruitment/applications",
    analyticsEndpoint: "/api/hrm/recruitment/applications/__analytics",
    statusField: "application_status",
    workflowActions: ["screen", "shortlist"],
  }),
  "hrm.enterprise.interviews": cfg("hrm.enterprise.interviews", "Interview Stages", "Interview schedules and stages.", "interview-stages", [
    { name: "recruitment_id", label: "Application", type: "select", selectEndpoint: "/api/hrm/recruitment/applications", selectLabel: ["candidate_name"], required: true, table: true },
    { name: "interview_stage", label: "Stage", required: true, table: true, defaultValue: "First Interview" },
    { name: "scheduled_at", label: "Scheduled", type: "datetime-local", table: true },
    { name: "location_or_link", label: "Location / Link" },
    { name: "status", label: "Status", table: true, defaultValue: "scheduled" },
  ], {
    endpoint: "/api/hrm/recruitment/interviews",
    analyticsEndpoint: "/api/hrm/recruitment/interviews/__analytics",
    workflowActions: [],
  }),
  "hrm.enterprise.feedback": cfg("hrm.enterprise.feedback", "Interview Feedback", "Ratings, recommendations, and hiring feedback.", "interview-feedback", [
    { name: "interview_id", label: "Interview", type: "select", selectEndpoint: "/api/hrm/recruitment/interviews", selectLabel: ["interview_stage"], required: true, table: true },
    { name: "panel_member_id", label: "Panel Member", ...employeeSelect, table: true },
    { name: "technical_score", label: "Technical", type: "number", table: true },
    { name: "culture_score", label: "Culture", type: "number", table: true },
    { name: "communication_score", label: "Communication", type: "number", table: true },
    { name: "experience_score", label: "Experience", type: "number", table: true },
    { name: "recommendation", label: "Recommendation", type: "select", options: ["hire", "hold", "reject"], table: true },
    { name: "comments", label: "Comments", type: "textarea" },
  ], {
    endpoint: "/api/hrm/recruitment/interview-feedback",
    analyticsEndpoint: "/api/hrm/recruitment/interview-feedback/__analytics",
    workflowActions: [],
  }),
  "hrm.enterprise.offerLetters": cfg("hrm.enterprise.offerLetters", "Offer Letters", "Offer letter preparation, sending, acceptance, and document links.", "offer-letters", [
    { name: "recruitment_id", label: "Application", type: "select", selectEndpoint: "/api/hrm/recruitment/applications", selectLabel: ["candidate_name"], required: true, table: true },
    { name: "offer_reference", label: "Offer No.", table: true },
    { name: "start_date", label: "Start Date", type: "date", required: true, table: true },
    { name: "salary_band", label: "Salary Band", table: true },
    { name: "base_salary", label: "Salary Offer", type: "number", table: true },
    { name: "benefits_summary", label: "Benefits", type: "textarea" },
    { name: "contract_end_date", label: "Contract End", type: "date" },
    { name: "probation_months", label: "Probation Months", type: "number", defaultValue: 6 },
    { name: "offer_expiry_date", label: "Offer Expiry", type: "date" },
    { name: "approval_status", label: "Approval", table: true, defaultValue: "pending" },
    { name: "offer_status", label: "Offer Status", table: true, defaultValue: "draft" },
  ], {
    endpoint: "/api/hrm/recruitment/offers",
    analyticsEndpoint: "/api/hrm/recruitment/offers/__analytics",
    statusField: "offer_status",
    workflowActions: ["approve", "send", "accept", "reject"],
    valueField: "base_salary",
  }),
  "hrm.recruitment.successfulApplicants": {
    key: "hrm.recruitment.successfulApplicants",
    title: "Successful Applicants",
    description: "Offer-accepted candidates ready for employee conversion.",
    endpoint: "/api/hrm/recruitment/successful-applicants",
    analyticsEndpoint: "/api/hrm/recruitment/successful-applicants/__analytics",
    searchFields: ["candidate_name", "candidate_email", "job_title", "department", "offer_status", "compliance_readiness", "document_readiness", "conversion_status"],
    statusField: "conversion_status",
    workflowActions: ["convert-to-employee"],
    fields: [
      { name: "candidate_name", label: "Candidate", table: true },
      { name: "candidate_email", label: "Email", table: true },
      { name: "job_title", label: "Job Title", table: true },
      { name: "department", label: "Department", table: true },
      { name: "branch", label: "Branch", table: true },
      { name: "employment_type", label: "Employment Type", table: true },
      { name: "target_start_date", label: "Start Date", type: "date", table: true },
      { name: "offer_status", label: "Offer", table: true },
      { name: "compliance_readiness", label: "Compliance", table: true },
      { name: "document_readiness", label: "Documents", table: true },
      { name: "conversion_status", label: "Conversion", table: true },
    ],
  },
  "hrm.enterprise.goals": cfg("hrm.enterprise.goals", "Goals", "Employee goals and achievement tracking.", "goals", [
    { name: "employee_id", label: "Employee", ...employeeSelect, required: true, table: true },
    { name: "goal_title", label: "Goal", required: true, table: true },
    { name: "goal_period", label: "Period", required: true, table: true },
    { name: "target_value", label: "Target", type: "number", table: true },
    { name: "achieved_value", label: "Achieved", type: "number", table: true },
    { name: "status", label: "Status", type: "select", options: ["draft", "active", "achieved", "missed"], table: true, defaultValue: "draft" },
  ], { valueField: "achieved_value" }),
  "hrm.enterprise.kpis": cfg("hrm.enterprise.kpis", "KPIs", "Department and employee KPIs with weight and actuals.", "kpis", [
    { name: "employee_id", label: "Employee", ...employeeSelect },
    { name: "department", label: "Department", type: "select", options: departmentOptions, table: true },
    { name: "kpi_name", label: "KPI", required: true, table: true },
    { name: "weight", label: "Weight", type: "number", table: true },
    { name: "target", label: "Target", type: "number" },
    { name: "actual", label: "Actual", type: "number", table: true },
    { name: "status", label: "Status", type: "select", options: ["active", "paused", "closed"], table: true, defaultValue: "active" },
  ], { valueField: "actual" }),
  "hrm.enterprise.reviewCycles": cfg("hrm.enterprise.reviewCycles", "Review Cycles", "Performance review cycle windows and status.", "review-cycles", [
    { name: "cycle_name", label: "Cycle", required: true, table: true },
    { name: "start_date", label: "Start", type: "date", required: true, table: true },
    { name: "end_date", label: "End", type: "date", required: true, table: true },
    { name: "status", label: "Status", type: "select", options: commonStatuses, table: true, defaultValue: "draft" },
  ]),
  "hrm.enterprise.competencies": cfg("hrm.enterprise.competencies", "Competencies", "Competency framework used in reviews.", "competencies", [
    { name: "competency_name", label: "Competency", required: true, table: true },
    { name: "competency_group", label: "Group", table: true },
    { name: "description", label: "Description", type: "textarea" },
    { name: "status", label: "Status", type: "select", options: ["active", "inactive"], table: true, defaultValue: "active" },
  ]),
  "hrm.enterprise.pips": cfg("hrm.enterprise.pips", "Improvement Plans", "Performance improvement plans and follow-up status.", "performance-improvement-plans", [
    { name: "employee_id", label: "Employee", ...employeeSelect, required: true, table: true },
    { name: "reviewer_id", label: "Reviewer", ...employeeSelect },
    { name: "start_date", label: "Start", type: "date", required: true, table: true },
    { name: "end_date", label: "End", type: "date" },
    { name: "improvement_area", label: "Improvement Area", type: "textarea", required: true },
    { name: "status", label: "Status", type: "select", options: commonStatuses, table: true, defaultValue: "draft" },
  ]),
  "hrm.enterprise.courses": cfg("hrm.enterprise.courses", "Courses", "Learning catalog and mandatory course settings.", "courses", [
    { name: "course_code", label: "Code", required: true, table: true },
    { name: "course_title", label: "Course", required: true, table: true },
    { name: "provider", label: "Provider", table: true },
    { name: "mandatory", label: "Mandatory", type: "checkbox", table: true },
    { name: "validity_months", label: "Validity Months", type: "number" },
    { name: "status", label: "Status", type: "select", options: ["active", "inactive"], table: true, defaultValue: "active" },
  ]),
  "hrm.enterprise.trainingSessions": cfg("hrm.enterprise.trainingSessions", "Training Sessions", "Scheduled sessions and completion status.", "training-sessions", [
    { name: "course_id", label: "Course", type: "select", selectEndpoint: "/api/hrm/enterprise/courses", selectLabel: ["course_title"] },
    { name: "session_title", label: "Session", required: true, table: true },
    { name: "facilitator", label: "Facilitator", table: true },
    { name: "start_date", label: "Start", type: "date", table: true },
    { name: "end_date", label: "End", type: "date" },
    { name: "status", label: "Status", type: "select", options: ["planned", "active", "completed", "cancelled"], table: true, defaultValue: "planned" },
  ]),
  "hrm.enterprise.certifications": cfg("hrm.enterprise.certifications", "Certifications", "Employee certifications and expiry tracking.", "certifications", [
    { name: "employee_id", label: "Employee", ...employeeSelect, required: true, table: true },
    { name: "certification_name", label: "Certification", required: true, table: true },
    { name: "issuing_body", label: "Issuing Body", table: true },
    { name: "issue_date", label: "Issue Date", type: "date" },
    { name: "expiry_date", label: "Expiry Date", type: "date", table: true },
    { name: "document_url", label: "Document URL" },
    { name: "status", label: "Status", type: "select", options: ["active", "expired", "revoked"], table: true, defaultValue: "active" },
  ]),
  "hrm.enterprise.trainingPolicies": cfg("hrm.enterprise.trainingPolicies", "Mandatory Training Policies", "Role and department-based training rules.", "mandatory-training-policies", [
    { name: "course_id", label: "Course", type: "select", selectEndpoint: "/api/hrm/enterprise/courses", selectLabel: ["course_title"], required: true, table: true },
    { name: "applies_to_department", label: "Department", type: "select", options: departmentOptions, table: true },
    { name: "applies_to_role", label: "Role", type: "select", options: roleCategories, table: true },
    { name: "renewal_frequency_months", label: "Renewal Months", type: "number" },
    { name: "status", label: "Status", type: "select", options: ["active", "inactive"], table: true, defaultValue: "active" },
  ]),
  "hrm.enterprise.companyAssets": cfg("hrm.enterprise.companyAssets", "Company Assets", "Asset register, custodians, cost, and status.", "company-assets", [
    { name: "asset_code", label: "Code", required: true, table: true },
    { name: "asset_name", label: "Asset", required: true, table: true },
    { name: "asset_category", label: "Category", table: true },
    { name: "serial_number", label: "Serial No." },
    { name: "purchase_date", label: "Purchased", type: "date" },
    { name: "purchase_cost", label: "Cost", type: "number", table: true },
    { name: "custodian_employee_id", label: "Custodian", ...employeeSelect, table: true },
    { name: "status", label: "Status", type: "select", options: ["available", "assigned", "maintenance", "disposed"], table: true, defaultValue: "available" },
  ], { valueField: "purchase_cost" }),
  "hrm.enterprise.clearance": cfg("hrm.enterprise.clearance", "Clearance Checklist", "Offboarding clearance items and departmental sign-offs.", "clearance-checklists", [
    { name: "employee_id", label: "Employee", ...employeeSelect, required: true, table: true },
    { name: "checklist_item", label: "Item", required: true, table: true },
    { name: "owner_department", label: "Owner Department", type: "select", options: departmentOptions, table: true },
    { name: "completed_by", label: "Completed By", ...employeeSelect },
    { name: "status", label: "Status", type: "select", options: ["pending", "completed", "waived"], table: true, defaultValue: "pending" },
  ]),
  "hrm.enterprise.exitInterviews": cfg("hrm.enterprise.exitInterviews", "Exit Interviews", "Exit interview records, reasons, and rehire eligibility.", "exit-interviews", [
    { name: "employee_id", label: "Employee", ...employeeSelect, required: true, table: true },
    { name: "interview_date", label: "Interview Date", type: "date", table: true },
    { name: "interviewer_id", label: "Interviewer", ...employeeSelect },
    { name: "reason_for_leaving", label: "Reason", type: "textarea" },
    { name: "rehire_eligible", label: "Rehire Eligible", type: "checkbox", table: true, defaultValue: true },
    { name: "notes", label: "Notes", type: "textarea" },
    { name: "status", label: "Status", type: "select", options: commonStatuses, table: true, defaultValue: "draft" },
  ]),
  "hrm.enterprise.terminations": cfg("hrm.enterprise.terminations", "Termination Records", "Termination records and approval workflow.", "termination-records", [
    { name: "employee_id", label: "Employee", ...employeeSelect, required: true, table: true },
    { name: "termination_type", label: "Type", type: "select", options: ["resignation", "termination", "retirement", "contract_end", "redundancy"], required: true, table: true },
    { name: "termination_date", label: "Date", type: "date", required: true, table: true },
    { name: "approved_by", label: "Approved By", ...employeeSelect },
    { name: "reason", label: "Reason", type: "textarea" },
    { name: "status", label: "Status", type: "select", options: commonStatuses, table: true, defaultValue: "draft" },
  ]),
  "hrm.enterprise.offboardingApprovals": cfg("hrm.enterprise.offboardingApprovals", "Offboarding Approvals", "Exit approvals across HR, Finance, IT, Legal, and managers.", "offboarding-approvals", [
    { name: "employee_id", label: "Employee", ...employeeSelect, required: true, table: true },
    { name: "approval_area", label: "Area", type: "select", options: ["HR", "Finance", "IT", "Legal", "Manager", "Facilities"], required: true, table: true },
    { name: "approver_id", label: "Approver", ...employeeSelect },
    { name: "comments", label: "Comments", type: "textarea" },
    { name: "status", label: "Status", type: "select", options: commonStatuses, table: true, defaultValue: "pending" },
  ]),
};

export const hrmModuleGroups = {
  organization: [
    "hrm.employees",
    "hrm.departments",
    "hrm.positions",
    "hrm.enterprise.companies",
    "hrm.enterprise.branches",
    "hrm.enterprise.costCenters",
    "hrm.enterprise.jobGrades",
    "hrm.enterprise.contracts",
    "hrm.enterprise.emergencyContacts",
  ],
  security: [
    "hrm.enterprise.roles",
    "hrm.enterprise.permissions",
    "hrm.enterprise.userLinks",
    "hrm.enterprise.auditLogs",
  ],
  leave: [
    "hrm.leave",
    "hrm.leaveBalances",
    "hrm.enterprise.leaveTypes",
    "hrm.enterprise.leavePolicies",
    "hrm.enterprise.leaveBlackouts",
  ],
  attendance: [
    "hrm.attendance",
    "hrm.enterprise.shifts",
    "hrm.enterprise.timesheets",
    "hrm.enterprise.overtime",
    "hrm.enterprise.holidays",
    "hrm.enterprise.attendancePeriods",
  ],
  payroll: [
    "hrm.payroll",
    "hrm.compensation",
    "hrm.enterprise.salaryStructures",
    "hrm.enterprise.payrollPeriods",
    "hrm.enterprise.payrollRuns",
    "hrm.enterprise.payslips",
    "hrm.enterprise.payrollComponents",
    "hrm.enterprise.payrollAdjustments",
  ],
  recruitment: [
    "hrm.recruitment",
    "hrm.enterprise.jobRequisitions",
    "hrm.enterprise.jobOpenings",
    "hrm.enterprise.candidates",
    "hrm.enterprise.applications",
    "hrm.enterprise.interviews",
    "hrm.enterprise.feedback",
    "hrm.enterprise.offerLetters",
    "hrm.recruitment.successfulApplicants",
  ],
  performance: [
    "hrm.performance",
    "hrm.enterprise.goals",
    "hrm.enterprise.kpis",
    "hrm.enterprise.reviewCycles",
    "hrm.enterprise.competencies",
    "hrm.enterprise.pips",
  ],
  training: [
    "hrm.training",
    "hrm.enterprise.courses",
    "hrm.enterprise.trainingSessions",
    "hrm.enterprise.certifications",
    "hrm.enterprise.trainingPolicies",
  ],
  assets: [
    "hrm.assetAssignments",
    "hrm.enterprise.companyAssets",
    "hrm.enterprise.clearance",
    "hrm.enterprise.exitInterviews",
    "hrm.enterprise.terminations",
    "hrm.enterprise.offboardingApprovals",
  ],
};
