SYSTEM_BLUEPRINT = {
    "name": "BusinessOS Version 2",
    "principle": "Every operational object is an entity that can be searched, linked, drilled into, analysed, and automated.",
    "domains": {
        "Sales CRM": [
            "Account",
            "Contact",
            "Lead",
            "Opportunity",
            "Deal",
            "Engagement",
            "Issue",
            "Quote",
            "Invoice",
            "SalesTarget",
        ],
        "Bids": ["Tender", "TenderDocument", "BidQualification", "BidResponse"],
        "Delivery PMO": ["Project", "SLA", "DeliveryTeam", "Milestone", "Stakeholder"],
        "Technical": ["TechnicalService", "Ticket", "Engineer", "Cluster", "Arena"],
        "HRM": ["Employee", "Department", "Payroll", "Leave", "Attendance", "Performance", "Training", "Benefit", "Document"],
        "Finance": ["Invoice", "Payroll", "BenefitCost", "TrainingCost", "DebtCollection", "GrossProfit"],
    },
    "relationships": [
        {"from": "Account", "to": "Contact", "type": "one-to-many"},
        {"from": "Account", "to": "Opportunity", "type": "one-to-many"},
        {"from": "Account", "to": "Deal", "type": "one-to-many"},
        {"from": "Account", "to": "Invoice", "type": "one-to-many"},
        {"from": "Account", "to": "Project", "type": "one-to-many"},
        {"from": "Account", "to": "SLA", "type": "one-to-many"},
        {"from": "Opportunity", "to": "Deal", "type": "one-to-many"},
        {"from": "Opportunity", "to": "Tender", "type": "optional-link"},
        {"from": "Deal", "to": "Project", "type": "one-to-many"},
        {"from": "Project", "to": "SLA", "type": "one-to-many"},
        {"from": "Project", "to": "Ticket", "type": "one-to-many"},
        {"from": "Employee", "to": "Department", "type": "many-to-one"},
        {"from": "Employee", "to": "Employee", "type": "line-manager"},
        {"from": "Employee", "to": "SalesTarget", "type": "AM-target"},
        {"from": "Employee", "to": "Account", "type": "AM-ownership"},
        {"from": "Employee", "to": "Project", "type": "delivery-ownership"},
        {"from": "Employee", "to": "Payroll", "type": "one-to-many"},
        {"from": "Employee", "to": "Benefit", "type": "one-to-many"},
    ],
    "engines": {
        "ExecutiveAnalyticsEngine": "Aggregates system-wide CRM, HRM, finance, delivery, SLA, tender, and workload metrics.",
        "GlobalSearchEngine": "Searches all operational entities and returns drill-down destinations.",
        "Staff360Engine": "Connects employee identity to departments, targets, accounts, projects, SLAs, tickets, payroll, and performance.",
        "WorkflowAutomationEngine": "Uses workflow policy records to drive reminders, approvals, handoffs, and completion queues.",
        "FinanceControlEngine": "Connects pipeline, deals, invoices, payroll, benefits, training cost, GP, and debt collection.",
    },
}
